site_name: R4Noobs
repo_url: 'https://github.com/SaLandini/r4noobs'
repo_name: 'R4Noobs'
theme:
  name: null
  custom_dir: mkdocs-windmill-dark-master/mkdocs_windmill_dark

nav:
  - Introdução: index.md
  - Configurando o Ambiente: configambiente.md
  - License: license.md

